import pandas as pd

a = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/DJI.csv")
b = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/DWDP.csv")
j = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/AXP.csv")
c = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/MMM.csv")
d = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/IBM.csv")
e = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/KO.csv")
f = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/MCD.csv")
g = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/GS.csv")
h = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/MSFT.csv")
i = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/TRV.csv")
k = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/PG.csv")
l = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/UTX.csv")
m = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/JPM.csv")
n = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/AAPL.csv")
o = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/DIS.csv")
p = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/BA.csv")
q = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/XOM.csv")
r = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/INTC.csv")
s = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/CAT.csv")
t = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/GE.csv")
u = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/V.csv")
v = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/NKE.csv")
w = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/CVX.csv")
x = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/CSCO.csv")
y = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/WMT.csv")
z = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/PFE.csv")
a1 = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/JNJ.csv")
a2 = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/HD.csv")
a3 = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/UNH.csv")
a4 = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/MRK.csv")
a5 = pd.read_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/VZ.csv")
merged = a.merge(b, on='Date').merge(c, on='Date').merge(d, on='Date').merge(e, on='Date').merge(f, on='Date').merge(g, on='Date').merge(h, on='Date').merge(i, on='Date').merge(j, on='Date').merge(k, on='Date').merge(l, on='Date').merge(m, on='Date').merge(n, on='Date').merge(o, on='Date').merge(p, on='Date').merge(q, on='Date').merge(r, on='Date').merge(s, on='Date').merge(t, on='Date').merge(u, on='Date').merge(v, on='Date').merge(w, on='Date').merge(x, on='Date').merge(y, on='Date').merge(z, on='Date').merge(a1, on='Date').merge(a2, on='Date').merge(a3, on='Date').merge(a4, on='Date').merge(a5, on='Date')
merged.to_csv("/Users/adityaprasann/IdeaProjects/PythonProj/downloaddata/output.csv", index=False)
